package com.team23.domain.enums

enum class BonusEnum {
    SIMPLE_HANDFUL_ATTACK,
    DOUBLE_HANDFUL_ATTACK,
    TRIPLE_HANDFUL_ATTACK,
    SIMPLE_HANDFUL_DEFENSE,
    DOUBLE_HANDFUL_DEFENSE,
    TRIPLE_HANDFUL_DEFENSE,
    ONE_AT_END_ATTACK,
    ONE_AT_END_DEFENSE,
    SLAM_ANNOUNCED,
    SLAM_NON_ANNOUNCED,
    SLAM_FAILED,
    SLAM_DEFENSE
}